seed: 42
device: 'cuda:0'
num_steps_per_env: 24
max_iterations: 2000
empirical_normalization: False

obs_groups:
  policy: ["policy"]
  critic: ["policy"]

policy:
  class_name: ActorCritic
  init_noise_std: 1.0
  actor_hidden_dims: [256, 128, 64]
  critic_hidden_dims: [256, 128, 64]
  activation: 'elu'
  actor_obs_normalization: False
  critic_obs_normalization: False

algorithm:
  class_name: PPO
  value_loss_coef: 1.0
  use_clipped_value_loss: True
  clip_param: 0.2
  entropy_coef: 0.01
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 1.0e-3
  schedule: 'adaptive'
  gamma: 0.99
  lam: 0.95
  desired_kl: 0.01
  max_grad_norm: 1.0

save_interval: 50
experiment_name: "so100_tracking"
run_name: ""
logger: "tensorboard"
neptune_project: "isaac_lab"
wandb_project: "isaac_lab"
log_dir: "logs"
